# Generated by Django 4.2 on 2023-08-01 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
        ('Cart', '0007_order_is_ordered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('type', models.CharField(max_length=50)),
                ('dishes', models.ManyToManyField(to='Cart.dishorder')),
            ],
        ),
        migrations.CreateModel(
            name='Banquet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('clients', models.ManyToManyField(to='Banquet.client')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Profile.profiledata')),
            ],
        ),
    ]
