# Generated by Django 4.2 on 2023-08-10 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_dish_rating'),
        ('Banquet', '0003_clientsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSampleDishOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.dish')),
            ],
        ),
    ]
