# Generated by Django 4.2 on 2023-08-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0004_clientsampledishorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsample',
            name='dishes',
            field=models.ManyToManyField(to='Banquet.clientsampledishorder'),
        ),
    ]
