# Generated by Django 4.2 on 2023-08-10 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0006_client_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='menu',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Banquet.clientsample'),
        ),
    ]
