# Generated by Django 4.2 on 2023-08-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0007_alter_client_menu'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientSample',
            new_name='MenuSample',
        ),
    ]
