# Generated by Django 4.2 on 2023-08-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0009_banquet_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquet',
            name='bonuses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='banquet',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='banquet',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='banquet',
            name='duration',
            field=models.DurationField(default=None),
        ),
    ]
