# Generated by Django 4.2 on 2023-08-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0010_banquet_bonuses_banquet_cost_banquet_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquet',
            name='addres',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='banquet',
            name='comment',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
