# Generated by Django 4.2 on 2023-08-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0011_banquet_addres_banquet_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquet',
            name='addres',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='banquet',
            name='bonuses',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='banquet',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='banquet',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='banquet',
            name='duration',
            field=models.DurationField(blank=True, default=None, null=True),
        ),
    ]
