# Generated by Django 4.2 on 2023-08-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0012_alter_banquet_addres_alter_banquet_bonuses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banquet',
            name='ordered_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
