# Generated by Django 4.2 on 2023-08-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0013_alter_banquet_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquet',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
