# Generated by Django 4.2 on 2023-08-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0014_banquet_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='banquet',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
