# Generated by Django 4.2 on 2023-09-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0016_banquet_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menusample',
            name='type',
            field=models.CharField(choices=[('Новогодний', 'Новогодний'), ('Свадебный', 'Свадебный'), ('День рождения', 'День рождения')], default=None, max_length=50, null=True),
        ),
    ]
