# Generated by Django 4.2 on 2023-09-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banquet', '0018_menusample_name_alter_menusample_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusample',
            name='name_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
