# Generated by Django 4.2 on 2023-08-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profiledata_patronymic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiledata',
            old_name='patronymic',
            new_name='number',
        ),
    ]
