# Generated by Django 4.2 on 2023-08-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_rename_patronymic_profiledata_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiledata',
            name='address',
        ),
        migrations.AddField(
            model_name='profiledata',
            name='patronymic',
            field=models.CharField(default='Отчество', max_length=20),
        ),
        migrations.AlterField(
            model_name='profiledata',
            name='number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
