# Generated by Django 4.2 on 2023-09-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_remove_profiledata_address_profiledata_patronymic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledata',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
