# Generated by Django 4.2 on 2023-07-26 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('Cart', '0003_order_address_order_delivery_time_order_wishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishorder',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Profile.profiledata'),
        ),
    ]
