# Generated by Django 4.2 on 2023-07-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0004_dishorder_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing '), ('Shipped', 'Shipped '), ('Delivered', 'Delivered  '), ('Cancelled', 'Cancelled '), ('On Hold', 'On Hold ')], default=None, max_length=10),
        ),
    ]
