# Generated by Django 4.2 on 2023-07-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_alter_order_address_alter_order_bonuses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
