# Generated by Django 4.2 on 2023-08-03 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
        ('Cart', '0009_alter_dishorder_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishorder',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profile.profiledata'),
        ),
    ]
