# Generated by Django 4.2 on 2023-07-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('brief_discription', models.TextField(blank=True, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calories', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, null=True)),
                ('is_vegetarian', models.BooleanField(blank=True, null=True)),
                ('weight_test', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='menu_images/<django.db.models.fields.CharField>')),
            ],
        ),
    ]
