# Generated by Django 4.2 on 2023-07-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_alter_dish_image_alter_dish_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='rating',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
