# Generated by Django 4.2 on 2023-09-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_dish_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='name_tags',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
