# Generated by Django 4.2 on 2023-09-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_dish_name_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='name_tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
